#!/bin/bash
# Para restaurarlo cambiar a sh

#CARD="${1:-0}"
#MIXER="${2:-default}"
#trap "echo Booh!" SIGHUP
#symbol=$(amixer -c $CARD -M -D $MIXER get Master | grep Playback | grep -q off && echo '' || echo ' ''  ')

#amixer -c $CARD -M -D $MIXER get Master |
#echo $(sed -n "s/^[^:]*: Playback [0-9]* \[\([0-9]*%\)\] .*/$symbol \1/p" | head -n1)
#echo ""
#echo $(amixer -c $CARD -M -D $MIXER get Master | grep Playback | grep -q off && echo "#F5A3A3" || echo "#EEEEEE")

pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 2 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' | SIZE=10 START="" END="" SEP="━" CHAR1="━" CHAR2="-" mkb


#while true; do
#    echo "%{c}%{F#7E7E7E}%{B#1C1C1C}  ⌚ $(Clock) | Ϟ$(Battery) | ▼ $(Wifi) | ♫ $(NowPlaying) | ◂⋑ $(Volume) %{F-}%{B-}"
#    sleep 0.1
#done
